#!/usr/bin/env python

import os
import csv
import sys
import time
from tokyo import cabinet

csv.field_size_limit(sys.maxsize)

db = cabinet.TDB()
mdb = cabinet.TDB()

db.open("dwc.db", cabinet.TDBOWRITER)
mdb.open("meta.db", cabinet.TDBOWRITER)

for key in db:
  print(key)
  record = db.get(key)
  try:
    meta = mdb.get(key)
  except:
    meta = None
  now = str(int(time.time()))
  if record:
    if meta and meta.get('created'):
      meta['updated'] = now
      mdb.put(key, meta)
    else:
      mdb.put(key, { 'created': now, 'updated': now })

